version: '3'

services:
  redis:
    image: redis:alpine
    container_name: Audify
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025